### ISSUE TITLE
Should pipeline test config be in YAML?

### ISSUE THREAD

**Issue by ycombinator** [elastic/package-spec#106]
The system test configuration is expressed as YAML and many other package files are also expressed as YAML. However, pipeline test configuration files (example: https://github.com/elastic/package-spec/blob/master/code/go/internal/validator/test/packages/good/data_stream/foo/_dev/test/pipeline/test-access-raw.log-config.json) is expressed as JSON. Should we change this to be YAML as well?

## Rollout plan for this change
* [x] Enhance package spec to allow `*.yml` pipeline test configuration files in addition to the currently-allowed `*.json` ones. Mark the `*.json` file format as deprecated (exactly how to do this is TBD). This will give package authors some time to adjust their pipeline test configuration file formats: https://github.com/elastic/package-spec/pull/139.
* [x] Update all pipeline test configuration files in the `integrations` repo from `*.json` => `*.yml`: https://github.com/elastic/integrations/pull/739.
* [x] Notify package stakeholders that `*.json` pipeline test configuration files are being removed and replaced by `*.yml` ones.
* [x] After a few weeks:
   * [x] Notify package stakeholders that support for `*.json` pipeline test configuration files is being removed.
   * [x] Remove support for `*.json` pipeline test configuration files from package spec: https://github.com/elastic/package-spec/pull/150.
   * [x] Notify package stakeholders that support for `*.json` pipeline test configuration files has been removed.

**Comment by andrewkroh** [comment]
I noticed this inconsistency and was wondering about it. +1 for using YAML for both.

**Comment by ycombinator** [comment]
I'm going ahead with this change now. I've updated the issue description with a plan on how to roll out this change safely. Please review it.

**Comment by mtojek** [comment]
@ycombinator I think you can move forward with this issue.

**Comment by ycombinator** [comment]
Thanks for the reminder, @mtojek. I'll move this forward today.

**Comment by ycombinator** [comment]
All steps in the rollout plan (see issue description) are now done. Closing.
