### ISSUE TITLE
Refactor transform package format

### ISSUE THREAD

**Issue by jonathan-buttner** [elastic/package-spec#109]
The transform format currently requires a directory and a file: https://github.com/elastic/endpoint-package/tree/master/package/endpoint/elasticsearch/transform/metadata_current

For example the link above requires the directory `metadata_current` and the actual transform file `default.json`. This could probably be refactored to only use a file. So the package path would look like:

`elasticsearch/transform/metadata_current_blah.json`.

**Comment by ruflin** [comment]
++ on cleaning this up. I think it is an onversight that transform contained an additional sub directory. It should be aligned with all the other assets. Would be nice if we find a way to clean this up without having to keep too much legacy code / spec definition.
