### ISSUE TITLE
Add support for icons in dark mode

### ISSUE THREAD

**Issue by hbharding** [elastic/package-spec#11]
Some icons like AWS, Kafka, IBM cloud, Github, etc. will not render well if a dark theme is used. In EUI, there is a mechanism for dealing with this, but since we're technically not using EUI icons (rather, we're defining our own custom ones which happen to be identical), we don't get this magic out of the box.

Since the majority of the icons we're using are already defined in EUI, it might be better if we just reference those icons by name instead, and only define custom icons when we need an icon that is not specified in EUI.

So in our manifest:

```
icons:
- src: /img/logo_postgres.svg
  title: logo postgres
  size: 32x32
  type: image/svg+xml
```

could become something much simpler like

```
icons:
- name: logoPostgres
```

I'm not sure why we need to define a title, size, and type. I think one caveat of referencing by name is that it places a dependency on EUI - meaning any consuming app that wants to see a package icon from the registry will need to have EUI setup.

![image](https://user-images.githubusercontent.com/847805/89543581-1ba19d80-d7cf-11ea-810f-3e16ae99e6ea.png)

![image](https://user-images.githubusercontent.com/847805/89543623-278d5f80-d7cf-11ea-8b4b-c7739d47d204.png)

**Comment by ycombinator** [comment]
> I'm not sure why we need to define a title, size, and type. 

I'll defer to @ruflin for why we need these fields today.

> one caveat of referencing by name is that it places a dependency on EUI - meaning any consuming app that wants to see a package icon from the registry will need to have EUI setup

Maybe we call this field `euiName` to make that dependency a bit more explicit?

**Comment by ruflin** [comment]
All the assets must be inside the package, we should not rely on logos from EUI. We did this in the past for the Add Data UI but stopped adding icons to EUI as it bloats EUI. Also it would mean anyone using this would rely on EUI which they shouldn't. Also AFAIK the plan is to remove all these logos from EUI one day.

For the size, icon and type: We used the same blocks we use for screenshots here. There title is definitively used and I think we also use size and type there. @jfsiii can comment more here. Even though we encourage to use svg, it is not the only type we support. We should not make it a burden for future contributors to require svg.

@hbharding Can a single svg contain the content for darkmode and non darkmode? If we need 2 icons, I suggest we introduce a flag in the config to indicate which one is which or rely on a naming convention.

**Comment by mtojek** [comment]
An old issue now, I guess we can close it.

**Comment by ruflin** [comment]
@mostlyjason Please reopen if Integrations page in dark mode has issues ...

**Comment by mostlyjason** [comment]
It still a problem because some icons like IIS and AWS are nearly unreadable. I don't necessarily think this is the highest problem though, so maybe leave it open but on the backlog?

![image](https://user-images.githubusercontent.com/6370704/142901040-7570ccac-2061-4805-8b40-bf63219f5511.png)
![image](https://user-images.githubusercontent.com/6370704/142901227-9a0fb107-b9f4-4d00-978b-89eafdd5cf23.png)
