### ISSUE TITLE
Replace ioutil usage

### ISSUE THREAD

**Issue by ycombinator** [elastic/package-spec#114]
With Go 1.16, the `ioutil` package is being deprecated: https://www.srcbeat.com/2021/01/golang-ioutil-deprecated/. We should start replacing its usage.

**Comment by u5surf** [comment]
@ycombinator 
I wanna work on this.
it'quit easy to replace following a few codes with new methods of which was stated

```
./code/go/internal/yamlschema/schema_loader.go:4:	"io/ioutil"
./code/go/internal/yamlschema/schema_loader.go:65:	itemSchemaData, err := ioutil.ReadAll(itemSchemaFile)
./code/go/internal/validator/folder_spec.go:5:	"io/ioutil"
./code/go/internal/validator/folder_spec.go:37:	data, err := ioutil.ReadAll(specFile)
./code/go/internal/validator/folder_spec.go:65:	files, err := ioutil.ReadDir(folderPath)
./code/go/internal/validator/folder_item_content.go:7:	"io/ioutil"
./code/go/internal/validator/folder_item_content.go:15:	itemData, err := ioutil.ReadFile(itemPath)
./code/go/internal/validator/package.go:5:	"io/ioutil"
./code/go/internal/validator/package.go:38:	data, err := ioutil.ReadFile(pkgManifestPath)
```

- ioutil.ReadAll -> io.ReadAll
-  ioutil.ReadDir -> os.ReadDir
- ioutil.ReadFile -> os.ReadFile

new methods: 

- https://github.com/golang/go/commit/cb0a0f52e67f128c6ad69027c9a8c7a5caf58446
- https://github.com/golang/go/commit/4f1b0a44cb46f3df28f5ef82e5769ebeac1bc493

**Comment by jlind23** [comment]
@mtojek @jsoriano should I close this issue?

**Comment by mtojek** [comment]
I will close this one.
