### ISSUE TITLE
[Change Proposal] Optional NOTICE.txt file for integrations

### ISSUE THREAD

**Issue by rw-access** [elastic/package-spec#149]
Related to #142

Some parts of these integrations could included code licensed with permissive licenses (MIT, BSD3, Apache 2, etc.). Even though the final license of all our integrations is Elastic License, Elastic License 2.0 or SSPL, we still have to preserve the original license notices when copying the code or binaries around.

We should have a generic way of including a NOTICE.txt file for each integration and deliver that to Kibana with the rest of the assets.. The most relevant use case currently is the Detection engine rules, which currently copy https://github.com/elastic/detection-rules/blob/main/NOTICE.txt into Kibana in https://github.com/elastic/kibana/blob/master/x-pack/plugins/security_solution/server/lib/detection_engine/rules/prepackaged_rules/notice.ts.

**Comment by ruflin** [comment]
From our other projects, I'm used to the `NOTICE.txt` file on the root level. Should we do the same for the packages to have an option `NOTICE.txt` file on the root level?

I wonder where in Kibana we should show this? I see you make it available in the detection rules but again I would consider this a generic feature. Maybe on the package view page, a user could click on a link to see it. It would still be possible to also show it on the rules page.

**Comment by rw-access** [comment]
> Maybe on the package view page, a user could click on a link to see it.

My thoughts exactly. That checks all the boxes for me.

**Comment by ruflin** [comment]
@rw-access Do you want to open a PR against package-spec directly. There we can pull in @mtojek and @ycombinator
