### ISSUE TITLE
[Change Proposal] Add support for explicitly defining dynamic_templates

### ISSUE THREAD

**Issue by axw** [elastic/package-spec#171]
In https://github.com/elastic/beats/pull/25422 we are extending `fields.yml` in libbeat to support explicitly defining dynamic_templates, for use with the `dynamic_templates` bulk request parameter introduced in Elasticsearch 7.13.0: https://github.com/elastic/elasticsearch/pull/69948. The purpose of this is to support dynamically mapping complex metrics, such as histograms and summaries. Naturally we would like to support this in integration packages too.

The above mentioned Beats PR introduces a new boolean "dynamic_template" property to fields in `fields.yml`. If this property is true, then the field represents a dynamic template rather than a concrete field. For example:

```yaml
- name: histogram_template
  type: histogram
  dynamic_template: true
```

This will result in an entry in the `dynamic_templates` section of the index template like this:

```json
"dynamic_templates": {
  "histogram_template": {
    "mapping": {
      "type": "histogram"
    }
  }
}
```

Tasks:
- [ ] Update the Kibana Fleet plugin's [template creation logic](https://github.com/elastic/kibana/blob/master/x-pack/plugins/fleet/server/services/epm/elasticsearch/template/template.ts) to understand the `dynamic_template` field property, creating dynamic templates (https://github.com/elastic/kibana/issues/102289)
- [x] Add `dynamic_template` to the [field schema](https://github.com/elastic/package-spec/blob/master/versions/1/data_stream/fields/fields.spec.yml) in package-spec (https://github.com/elastic/package-spec/issues/187)

**Comment by ruflin** [comment]
++ on adding support for this. @exekias Do we already have packages where this could become useful?

**Comment by exekias** [comment]
Yes! Thanks for opening @axw, the obvious one will be Prometheus, where we can use this to get rid of the suffixes to match types. @ChrsMark FYI.

I'm +1 to getting this in as it is, as it matches what we have in Beats after elastic/beats#25422

**Comment by axw** [comment]
Seems we have consensus so I've removed the discuss label, created implementation issues, and added checkboxes.

**Comment by simitt** [comment]
cc @jen-huang for visibility.

**Comment by axw** [comment]
I'm going to close this and revert the change to package-spec. It occurred to me that we an define the dynamic templates directly in the data stream manifest. See https://github.com/elastic/kibana/issues/102289#issuecomment-904640242
