### ISSUE TITLE
[Discuss] Impact of renaming dataset to data_stream

### ISSUE THREAD

**Issue by ruflin** [elastic/package-spec#18]
It was decided recently to rename the `dataset.*` fields to `data_stream.*` fields and quite a few changes were already made for this in 7.9. No changes have happened in the package spec so far. This issue is to discuss what impact this rename has on the package spec.

**Comment by ruflin** [comment]
One of the places where `dataset` shows up is the directory `dataset`. Should this be renamed to `data_stream` as all the assets in there are related to `data_stream.*` what was before `dataset`. This change would also impact the `manifest.yml` files for each dataset. For example there is the `name` [property](https://github.com/elastic/package-registry/blob/master/testdata/package/reference/1.0.0/dataset/reference/manifest.yml) which in the past described `dataset.name` which now has become `data_stream.dataset`. `type` property would fit again if we rename it to `data_stream`. 

Are there other parts which would need adjustment? Is the above change worth it to clean up things?

@ycombinator @mtojek Would be great to get your input on these and if you see other parts where names should be changed.

**Comment by mtojek** [comment]
Items to be adjusted:

[ ] integration `dataset` directory
[ ] Integrations docs
[ ] import-beats script

Feel free to modify this post if you remind more items. It would be cool to combine it with potential other changes (not sure if config policy is a good candidate).

**Comment by ycombinator** [comment]
@ruflin @mtojek I created #24 to show the changes to the spec. Please take a look.
