### ISSUE TITLE
Use "embed" introduced in go 1.16

### ISSUE THREAD

**Issue by mtojek** [elastic/package-spec#180]
The goal of this issue is to use "embed" feature available in the go 1.16.

Suggested in: https://github.com/elastic/package-spec/pull/179#discussion_r643742621

**Comment by ycombinator** [comment]
Duplicate of https://github.com/elastic/package-spec/issues/99.

**Comment by mtojek** [comment]
Resolving in favor of https://github.com/elastic/package-spec/issues/99
