### ISSUE TITLE
[Discuss] Impact of renaming config to policy

### ISSUE THREAD

**Issue by ruflin** [elastic/package-spec#19]
It was decided to rename Agent Config to Agent Policy. This also applies to all config blocks inside the config blocks inside the config, which are now also policies.

The main usage of config inside the package spec seems to be `config_template` which could become `policy_template` instead.

**Comment by ruflin** [comment]
@mtojek @ycombinator Thoughts on the above? Perhaps this is also an opportunity to find a better name?

**Comment by mtojek** [comment]
> It was decided to rename Agent Config to Agent Policy. This also applies to all config blocks inside the config blocks inside the config, which are now also policies.

It would be valuable to put a sample config here as the description is a bit blurry. What are the policies? How much do they differ from what we have now?

**Comment by ruflin** [comment]
Policy = Config. There is no difference form a pure yaml perspective structure except the name. One thing that changes is if `dataset.*` was used inside the stream templates it now has to be `data_stream.*`, but this is specific to each package and only effected the log package so far.

**Comment by ycombinator** [comment]
Yeah, I'm also not 100% clear on what are agent configs in relation to packages. To put it differently: where exactly in packages do agent configs show up? It might be helpful to post some links to agent configs in existing packages.

**Comment by ruflin** [comment]
An example config can be found here: https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/elastic-agent.yml But lets also try to talk it through, I organised a meeting tomorrow and then we follow up here.

**Comment by ycombinator** [comment]
@ruflin @mtojek I think we can close this now thanks to https://github.com/elastic/package-spec/pull/50?

**Comment by mtojek** [comment]
Yes. Resolving.
