### ISSUE TITLE
Add validation that owner is set

### ISSUE THREAD

**Issue by ruflin** [elastic/package-spec#20]
The owner of a package is becoming more important. I think every package "must" specify an owner. The owner can be a group or a single person. The validation script should be able to validate that an owner exists. 

An addition to that would be that it even validates if the group / users exists on Github but that might become excessive and cause permissions problems.

**Comment by ycombinator** [comment]
> The validation script should be able to validate that an owner exists.

Concretely what does it mean for an owner to exist? Are owners the same as a user or repo on GitHub? Or is it a team on GitHub? Based on what you said about permissions I think an owner is either a user or team on GitHub — if so, then yes, we could probably validate the existence of a user but not that of a team.

**Comment by ruflin** [comment]
Yes, owner should be user or team.

**Comment by jsoriano** [comment]
Owner is already required, and we also enforce the presence of the owners in the GITOWNERS file in the integrations repository. Closing this. Please reopen if something is missing.
