### ISSUE TITLE
[Change Proposal] Add option to process fields for metric type data streams

### ISSUE THREAD

**Issue by narph** [elastic/package-spec#201]
Hitting the following scenario:

Migrating the `compute_vm` (light) metricset to data stream. This time we want to reduce the number of metrics we collect. This is not possible atm so we are using the origin metricset `monitor` to list the desired metrics.
All seems to be working but the events will show the name of the origin metricset instead of the `compute_vm`.

Ex manifest file for `compute_vm`:

```
metricsets: ["monitor"]
default_resource_type: "Microsoft.Compute/virtualMachines"
add_cloud_metadata: true
period: {{period}}
{{#if client_id}}
client_id: {{client_id}}
{{/if}}
.....
```

Example event:
```
 {
        "_index" : ".ds-metrics-azure.compute_vm-default-2021.07.20-000001",
        "_type" : "_doc",
        "_id" : "gKQMxHoBNET1TylT2jVH",
        "_score" : 1.0,
        "_source" : {
        .....
          "data_stream" : {
            "namespace" : "default",
            "type" : "metrics",
            "dataset" : "azure.compute_vm"
          },
          "metricset" : {
            "period" : 300000,
            "name" : "monitor"
          },
          "event" : {
            "duration" : 1494486800,
            "agent_id_status" : "verified",
            "ingested" : "2021-07-20T13:13:34.338318200Z",
            "module" : "azure",
            "dataset" : "azure.compute_vm"
          },
          "azure" : {
            "subscription_id" : "70bd6e77-4b1e-4835-8896-db77b8eef364",
            "timegrain" : "PT5M",
            "resource" : {
              "name" : "obslinux",
              "id" : "/subscriptions/70bd6e77-4b1e-4835-8896-db77b8eef364/resourceGroups/obs-infrastructure/providers/Microsoft.Compute/virtualMachines/obslinux",
              "type" : "Microsoft.Compute/virtualMachines",
              "group" : "obs-infrastructure"
            },
            "namespace" : "Microsoft.Compute/virtualMachines",
            "monitor" : {
              "inbound_flows_maximum_creation_rate" : {
                "avg" : 181
              },
              "disk_read_bytes" : {
                "total" : 2280634.01
              },
              "percentage_cpu" : {
                "avg" : 7.466666666666666
              },
              "network_in" : {
                "total" : 915698
              },
              "network_in_total" : {
                "total" : 1713469.0
              },
              "outbound_flows_maximum_creation_rate" : {
                "avg" : 181
              }
            }
          }
        }
      },
```

Metrics should be under `compute_vm` and not `monitor`.

There is no solution atm that we can use in order to rename the fields at the integration level.

The only workarounds are either adapting the `compute_vm` metricset inside the azure module to accept a list of metrics or adapt the `monitor` metricset to return metrics under a different object name.
Both solutions require delaying integration migration as we need to wait for the changes to be released, also other contributors might encounter this situation in other integrations.
Can we find a solution at the package level for this so we can avoid this situation for other migrations?

cc @sorantis

**Comment by mtojek** [comment]
cc'ing more people as we may need to brainstorm here

cc @jen-huang @jsoriano @ruflin

**Comment by exekias** [comment]
This issue is caused by switching from lightweight modules to data streams. In that switch we drop the concept of metricset, which was used by the `monitor` input to [place metrics in under the metricset namespace](https://github.com/elastic/beats/blob/9fb0b4571805a9a1c23167a97daee1465ffcef1e/x-pack/metricbeat/module/azure/data.go#L100).  If I understand things right, this is more of a problem at the input level.

The way I see it, packages are not in charge of automatically handling this, but there are a few things we can do today:

- Use an ingest pipeline to do the [rename](https://www.elastic.co/guide/en/elasticsearch/reference/master/rename-processor.html) (`monitor` -> `compute_vm`), this solves the problem for now, and doesn't require a new version of the agent for it to work.
- Add a parameter to the input so we can define what's the desired namespace

These two things can happen in parallel, and the ingest rename part can be removed after the parameter is in and properly configured by the integration.

**Comment by mtojek** [comment]
> Use an ingest pipeline to do the rename (monitor -> compute_vm), this solves the problem for now, and doesn't require a new version of the agent for it to work.

Is it possible to define an ingest pipeline for the metrics-type data streams? So far we're using it only for logs-type data streams.

**Comment by narph** [comment]
@mtojek , that's what I thought as well and I tested it out, seems to work.
```
"azure" : {
            "subscription_id" : "70bd6e77-4b1e-4835-8896-db77b8eef364",
            "timegrain" : "PT5M",
            "resource" : {
              "name" : "obslinux",
              "id" : "/subscriptions/70bd6e77-4b1e-4835-8896-db77b8eef364/resourceGroups/obs-infrastructure/providers/Microsoft.Compute/virtualMachines/obslinux",
              "type" : "Microsoft.Compute/virtualMachines",
              "group" : "obs-infrastructure"
            },
            "namespace" : "Microsoft.Compute/virtualMachines",
            "compute_vm" : {
              "inbound_flows_maximum_creation_rate" : {
                "avg" : 181
              },
              "disk_read_bytes" : {
                "total" : 2484808.1
              },
              "network_in" : {
                "total" : 1234290.0
              },
              "percentage_cpu" : {
                "avg" : 14.26375
              },
```
This will work  great for now, until we find a nice solution on the input side.

**Comment by exekias** [comment]
> Is it possible to define an ingest pipeline for the metrics-type data streams? So far we're using it only for logs-type data streams.

I consider this a desirable feature. We can use ingest pipelines to do things like keeping backwards compatibility (rename fields from old agents, drop fields we are no longer interested on), also enriching.

I don't see any reason to forbid pipelines in metrics data_streams

**Comment by exekias** [comment]
Should we close this one? not sure there is any pending action at the spec level

**Comment by narph** [comment]
I will close this since there is a temp solution to post process metric fields at package level
