### ISSUE TITLE
Add support for dimension fields

### ISSUE THREAD

**Issue by jsoriano** [elastic/package-spec#215]
Dimensions in time series databases are used to identify different time series. Metrics in documents with the same set of dimensions are considered the same time serie. Metrics with different set of dimensions are different time series.
This is specially relevant relevant when querying time series.

There is an effort in Elasticsearch to include dimensions as first-class citizens (see https://github.com/elastic/elasticsearch/issues/74014, https://github.com/elastic/elasticsearch/pull/74450), what will have advantages when storing and consuming time series data. To leverage these features in integrations, their dimensions should be properly defined.

For that we could add a new boolean property "`dimension`". Fields with this property set to true will be considered dimensions, any other field will be considered fields, or tags in the case of other metadata.

Not all types of metrics can be dimensions (to confirm what types can be dimensions).

**Comment by exekias** [comment]
++ on this, and the proposed `dimension` property under `fields.yml`.

If I understand latest changes, this would translate into a `time_series_dimension` mapping parameter. (BTW we may also need to update metric_type mapping once things get in).

Do you know if this already scheduled for a release on the ES side?

**Comment by jsoriano** [comment]
> Do you know if this already scheduled for a release on the ES side?

I think it is targeted for 7.16, see https://github.com/elastic/elasticsearch/pull/74450
