### ISSUE TITLE
[Change Proposal] Add support for specifying cluster privileges

### ISSUE THREAD

**Issue by stuartnelson3** [elastic/package-spec#224]
This proposal is a continuation of work that was initially begun with https://github.com/elastic/package-spec/issues/203.

In that issue it was decided to add `elasticsearch.privileges.indices`, but not specifically cluster privileges.

As was recently surfaced in https://github.com/elastic/beats/issues/28164, access to specific cluster privileges are required for apm-server's stack monitoring ui to correctly while while being managed by elastic-agent.

The specific problem is that the `cluster:monitor/main` privilege is required.

I could use some additional insight from others on the specifics of how to achieve this. Assuming this is approved, I have a few questions:

- Where would this should be added to package spec? The current implementation seems datastream-focused, while this would be specifically so that the apm-server is able to request data from elasticsearch's root path.
- Would this require additional changes to kibana? Again, the [linked code](https://github.com/elastic/kibana/blob/e771748d96ba098e2e35cf98a010f4f2a23c9c39/x-pack/plugins/fleet/common/types/models/epm.ts#L300) from the previous issue makes me believe it is data-stream focused

However it ends up being structured, I think the original proposal's core looks like a good start:

```yaml
elasticsearch:
  privileges:
    cluster: ['monitor/main']
```

**Comment by stuartnelson3** [comment]
@jen-huang assuming this goes through, would you have bandwidth to get the necessary changes in on the kibana side by FF on oct 19?

**Comment by ruflin** [comment]
Package manifest sounds like a good place for me as it seems it does not tie into a specific data stream.

**Comment by stuartnelson3** [comment]
I'm going to go ahead and call this "accepted". I'll create implementation issues and then move forward from there.

**Comment by jsoriano** [comment]
Closing this as it seems it was already implemented in https://github.com/elastic/package-spec/pull/226. Please reopen if there was anything pending to do.
