### ISSUE TITLE
Discuss: package compatibility with v8.1, v8.2 and next

### ISSUE THREAD

**Issue by mtojek** [elastic/package-spec#228]
Hi,

here is another question:

> So far integrations define Kibana constraint as ^7.16.0 (general pattern), which means that they won’t be available in Kibana v8.0.0. Do we need to roll out all integrations with appropriate Kibana version constraints?

@ruflin 's response:

> We don't know today if a package that is shipped now will be compatible with 8.1 or 8.2 as there might be breaking changes in 8.0 still.

The goal of this issue is to decide about compatibility rules between different minors. I'm not sure who should be cc'd, let me start with @mostlyjason and @akshay-saraswat  .

**Comment by jsoriano** [comment]
I think that from a packages developer perspective we should assume that a package that works with 8.x is going to work with any 8.y version (for y>=x), the alternative means that breaking changes can be introduced on its dependencies (Beats/Agent/Fleet/Kibana) at any moment, what shouldn't happen. And this would also imply the need to re-release and test all the packages with every minor, what is not sustainable.

Note: yes, breaking changes can happen during 8.x in dependencies of a package (_make it minor_), but they should be notified in advance and probably many versions ahead. During this time new versions of the affected packages should be eventually published to adapt to these changes. These should be exceptional situations, in general package developers should feel safe about using `^8...` constraints.

**Comment by jsoriano** [comment]
Is there something to do about this? We have other issues about handing breaking changes, deprecations and so on.

**Comment by mtojek** [comment]
I guess that we can close it now.
