### ISSUE TITLE
[Change Proposal] Support `deprecated` as a type of package release

### ISSUE THREAD

**Issue by jamiehynds** [elastic/package-spec#242]
The Security Integrations team have a number of integrations which have been marked as deprecated, but still appear in the UI. These are integrations that began as experimental integrations, but deprecated in favour of new integrations built from scratch. Others are integrations which were previously bundled into a single integration, but have since been separated into multiple integrations. We have a [set of experimental integrations](https://github.com/elastic/integrations/issues/1733) which will also be deprecated in the future. 

We'd like to avoid having these deprecated packages appear in the UI for the duration of the 8.x series, and would prefer not to carry them over to 8.0. However, this impacts users running those deprecated packages today. Could we add functionality in Fleet whereby, deprecated packages do not appear in the UI, but will continue to run in users environments upon upgrade to 8.0? 

This would ensure users would not be impacted during the 8.0 upgrade (i.e. data loss due to the package not starting). They would have to manually switch to a new package, but this approach would minimise the impact. 

To start, we can add `deprecated` as a type of release in the package spec, so that Integrations UI in Kibana can handle the visibility of such packages accordingly:
https://github.com/elastic/package-spec/blob/1a62673edc911514c7af348bceb658d82af85973/versions/1/manifest.spec.yml#L146-L152

**Comment by jen-huang** [comment]
Thanks Jamie! I transferred this to the package-spec repo as I think that's the best place to continue this discussion. I updated the original description to include what I think needs to change in the spec first before Kibana can follow up on the UI changes. Would be good to get feedback from the integrations team about this proposal.

**Comment by jamiehynds** [comment]
Thanks so much @jen-huang. 

@akshay-saraswat would be great to get input from you and/or an engineer on your team also. 

@P1llus has given a +1 from the Security Integrations team, but tagging @andrewkroh for visibility.

**Comment by mtojek** [comment]
Hi,

there is already a thread about deprecation path for packages, so I will resolve this one. Could you please comment in: https://github.com/elastic/package-spec/issues/227 ?

Resolving
