### ISSUE TITLE
[Change Proposal] Stricter validation on fields properties

### ISSUE THREAD

**Issue by jsoriano** [elastic/package-spec#282]
We have found that it is pretty common (https://github.com/elastic/integrations/issues/2643) to have typos in fields properties. This can be an important issue because this may create unexpected field mappings, and fixing mappings uses to bring breaking changes.

In https://github.com/elastic/package-spec/pull/281 I explore the enforcement of stricter validation, but there I found that at least for the `example` field we would need some trade offs.

**Comment by andrewkroh** [comment]
There is a misalignment between the spec and what Fleet accepts for field definitions. I think these two should be sync'ed while enabling the stricter validation. 

https://github.com/elastic/kibana/blob/b4b3285643dd9105e4c34883e8c032e771ee5fcb/x-pack/plugins/fleet/server/services/epm/fields/field.ts#L14

**Comment by endorama** [comment]
This bit us multiple times, would be great to have it! It also makes onboarding quite difficult: knowing and navigating the package spec is complex and any error slips through validation. 

Would be very useful for package devs to have this in the form of warnings (for example as part of package linting). Having a soft check that does not break the integration may also be helpful for adapting integrations before forcing this in the CI (as I expect multiple integrations would not pass this check at first).

**Comment by jsoriano** [comment]
@endorama stricter validation is coming in package-spec v2 :) https://github.com/elastic/package-spec/pull/420
This will make CI fail though, but package developers can choose when to change the `format_version` to take advantage of these new validations. You will have more news about this soon.

Regarding docs, yes, this is another pending thing we have. I was thinking on generate more easily consumable docs from the spec (https://github.com/elastic/package-spec/issues/400), I hope to work on this soonish.
