### ISSUE TITLE
 Warning when assets are built with a stack SNAPSHOT version

### ISSUE THREAD

**Issue by ruflin** [elastic/package-spec#318]
We recently had some issues with some dashboards and visualisations based off a snapshot version of the stack. Snapshot builds can contain bugs which can lead to invalid dashboards / visualisations exported.

The general recommendation is to build dashboards and visualisations off stable versions of the stack. But this is not always possible as a feature is needed that is only released in the next minor but I expect this to be the exception.

The saved objects normally contain some information related to from which version of the stack these were exported from (https://github.com/elastic/package-storage/blob/production/packages/apache/1.3.5/kibana/dashboard/apache-Logs-Apache-Dashboard.json#L15). If this info is incorrect, we should work with the Kibana team to have this more standardised (@flash1293 ). If this version contains a `-SNAPSHOT` string, a warning should be raised.

Dashboards and visualisations for a package should always be built with the minimal version of the stack that it is compatible with. So if a package is compatible with 8.0, this is the version that dashboards should be built with. This is an additional point that can be validated that assets are not newer then the minimal supported stack version.

**Comment by jsoriano** [comment]
Something we could do is to disallow having resources built with `-SNAPSHOT` in stable versions of packages. Though this may complicate development of packages aligned with stack releases.

**Comment by ruflin** [comment]
An idea brought up today by @joshdover related to a different issue was around using label. This could work here as well. The logic I could see happening:

* Prerelease package versions are allowed to contain -SNAPSHOT
* Stable versions are not allowed to contain -SNAPSHOT
* Stable versions can contain -SNAPSHOT if `allow_snapshot` label is added

This will allow development of prerelease packages based on prelease release. If it should be released with the iteration, the dashboards should be exported again after FF. The same is true for bundled packages. One question around this: What happens if you run export dashboard on a RC, will it contain -SNAPSHOT?

**Comment by mrodm** [comment]
I have some doubts about which field should it be considered to get the Elastic stack version that was used to build the assets from. Maybe @flash1293 , could you help me with this ? or redirect me to some doc about it ?

- What is the difference between `coreMigrationVersion` and `migrationVersion`?
    - I've checked that those fields could have different versions, Should we focus on `migrationVersion` field to get the version?
    - Example:
        - [Different versions](https://github.com/elastic/integrations/blob/main/packages/zscaler_zpa/kibana/visualization/zscaler_zpa-552331e0-4c4f-11ec-9023-a76a2cb41dcd.json#L76-L80)
        - [prometheus visualization - No coreMigrationVersion](https://github.com/elastic/integrations/blob/main/packages/prometheus/kibana/visualization/prometheus-d7740b40-b2fc-11e9-9a23-67ee28886a4b.json#L114) 

- In case of dashboards assets, I've checked that each panel defined in `panelsJSON` has also a `version` field on it. What field should be taken into consideration if version field in `panelsJSON` objects show a different version from `migrationVersion`?
    - Examples:
        - Panels with SNAPSHOT version:
            - migrationVersion non-SNAPSHOT **7.14.0**: [elastic_agent dashboard migrationVersion field](https://github.com/elastic/integrations/blob/main/packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json#L236)
            - panels defined under `panelsJSON` version **7.15.0-SNAPSHOT**: [elastic_agent dashboard panel version](https://github.com/elastic/integrations/blob/main/packages/elastic_agent/kibana/dashboard/elastic_agent-f47f18cc-9c7d-4278-b2ea-a6dee816d395.json#L226)
        - Panels with other stable versions:
             - Version from migrationVersion field **8.1.0**: [æws dashboard migrationVersion field](https://github.com/elastic/integrations/blob/main/packages/aws/kibana/dashboard/aws-562bdea0-4ba7-11ec-8282-5342b8988acc.json#L1719)
            - Version panel **7.15.1**:  [aws dashboard panel](https://github.com/elastic/integrations/blob/main/packages/aws/kibana/dashboard/aws-562bdea0-4ba7-11ec-8282-5342b8988acc.json#L1539)

- There are assets without `migrationVersion` field. As there is no information, I was thinking to skip those files from the validation. Should we show also a warning that it does not exist ?  
    - Example assets:
        - [dga security_rule](https://github.com/elastic/integrations/blob/main/packages/dga/kibana/security_rule/997ec71d-bddc-4513-b6f1-193f601fd420.json)
        - [system visualization](https://github.com/elastic/integrations/blob/main/packages/system/kibana/visualization/system-855899e0-1b1c-11e7-b09e-037021c4f8df.json)
        - [system dashboard](https://github.com/elastic/integrations/blob/main/packages/system/kibana/dashboard/system-79ffd6e0-faa0-11e6-947f-177f697178b8.json)
            - in this case, panels defined `panelsJSON` have a [version field (7.6.0)](https://github.com/elastic/integrations/blob/main/packages/system/kibana/dashboard/system-79ffd6e0-faa0-11e6-947f-177f697178b8.json#L31).
    - Others assets where it does not exist: search, tag, ml_module, osquery_saved_query, osquery_pack_asset, index_pattern or csp_rule_template

**Comment by flash1293** [comment]
I'm not 100% sure about the version in the `panelsJSON` - @ThomThomson could you help out here clarifying what's exactly the meaning of a version showing up in a specific place in the dashboard saved object?

**Comment by mrodm** [comment]
@flash1293 @ThomThomson taking into account https://github.com/elastic/package-spec/issues/318#issuecomment-1246488183 , as a first approach to get the version of the Elastic stack used to generate the assets of a package, would it be right to take the value of `migrationVersion` field (if it exists) as the version of the Elastic stack?

One option that I'm exploring in https://github.com/elastic/package-spec/pull/418 would be:
1. retrieve all the versions obtained by
    1. Get version from `migrationVersion` field, if it exists.
    2. Get versions from every panel under `attributes.panelsJson`, if any. IIRC this would be just applicable for dashboard assets.
        - Each panel could have a different version.
        - Example: 
            - This [aws dashboard](https://github.com/elastic/integrations/blob/main/packages/aws/kibana/dashboard/aws-562bdea0-4ba7-11ec-8282-5342b8988acc.json) contains panels with version 7.15.1, 8.0.0 and 8.1.0                             
2. With this list of versions, check if any of them contains SNAPSHOT as a prerelease tag.

Would that process make sense ? Or, should I just use `migrationVersion` value ?

**Comment by ThomThomson** [comment]
Hey @mrodm, the version information in panels should be ignored IMO. I think you should be fine sticking to `migrationVersion`.

I'm honestly not sure why some dashboards have multiple versions, because the migration function should _always_ return the current version when the migrations are run for each panel.

See the converter that panels get run through on migration [here](https://github.com/elastic/kibana/blob/672bdd25b44dd18511a1e0faeb1366ef3640e04f/src/plugins/dashboard/common/embeddable/embeddable_saved_object_converters.ts#L29)

**Comment by mrodm** [comment]
> Hey @mrodm, the version information in panels should be ignored IMO. I think you should be fine sticking to `migrationVersion`.
>
> I'm honestly not sure why some dashboards have multiple versions, because the migration function should _always_ return the current version when the migrations are run for each panel.
> 
> See the converter that panels get run through on migration [here](https://github.com/elastic/kibana/blob/672bdd25b44dd18511a1e0faeb1366ef3640e04f/src/plugins/dashboard/common/embeddable/embeddable_saved_object_converters.ts#L29)

Ok, I'll focus on this `migrationVersion` field :+1: 
Thanks @ThomThomson !

**Comment by mrodm** [comment]
As discussed in this thread https://github.com/elastic/package-spec/pull/418#discussion_r975177941 , this check is going to be performed by the `elastic-package export` command (https://github.com/elastic/elastic-package/pull/986).

This command is going to detect if the dashboards/assets are being exported from a Elastic stack SNAPSHOT version:
- If it is a from a SNAPSHOT version, it will shown an Error with a descriptive message.
- Developers could export those dashboards, if they set `--allow-snapshot` parameter into the command explicitly.
