### ISSUE TITLE
[Discuss] Elasticsearch and Elastic Agent conditions

### ISSUE THREAD

**Issue by ruflin** [elastic/package-spec#334]
Today each package has a condition with the minimal Kibana version it is able to run on. This looks as following:

```
conditions:
  kibana.version: "^7.16.0 || ^8.0.0"
```

This is currently the [only condition supported](https://github.com/elastic/package-spec/blob/ff81936f9495f64c26722314e5e86355f575f92f/versions/1/integration/manifest.spec.yml#L161). In the early days of packages there were also Elasticsearch and Elastic Agent conditions but got removed to reduce the complexity and just assume Elasticsearch, Kibana and Elastic Agent are in sync or Elastic Agent is older.

This worked well in the early days as now new inputs showed up in Elastic Agent, but this started to change. It is well possible that an older Elastic Agent does not have the inputs needed for a specific integration and there is no way for a package developer to specify a minimal Elastic Agent version.

For Elasticsearch, it should always be in sync with Kibana but there are upgrade scenarios / roll back where this is not the case. Are there any cases where we need a required Elasticsearch version?

This issue is to discuss if it is worth thinking through the scenarios of having conditions for Elastic Agent and Elasticsearch and what the side effects for Fleet (@joshdover ) would be of this.

**Comment by jsoriano** [comment]
Issue discussed also in https://github.com/elastic/package-spec/issues/165.

**Comment by ruflin** [comment]
Closing in favor of https://github.com/elastic/package-spec/issues/165 as this is a duplicate. @jsoriano thanks for pointing it out.
