### ISSUE TITLE
Validate supported inputs

### ISSUE THREAD

**Issue by ruflin** [elastic/package-spec#34]
The Elastic Agent supports a limited number of inputs. On the logs side these are: https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/spec/filebeat.yml#L62 There are more for metrics. We should find a way to validate as good as possible the valid input types in packages.

**Comment by ycombinator** [comment]
@ruflin Is this different from #32 or the same?

**Comment by ruflin** [comment]
This is a duplicate :-( Closing in favor or https://github.com/elastic/package-spec/issues/32
