### ISSUE TITLE
Input packages - Elastic Package to facilitate testing methods

### ISSUE THREAD

**Issue by jlind23** [elastic/package-spec#361]
Add system test around input packages usage.

- [x] Add definitions to the spec
  - https://github.com/elastic/package-spec/pull/443
- [ ] Add support in `elastic-package`
  - https://github.com/elastic/elastic-package/pull/1041

**Comment by jsoriano** [comment]
UIs already have basic support for input packages (https://github.com/elastic/kibana/issues/137750), so I guess we can unblock this.
