### ISSUE TITLE
[Change Proposal] Add support for Aggregate metric fields

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/package-spec#363]
See: https://www.elastic.co/guide/en/elasticsearch/reference/current/aggregate-metric-double.html

The current spec does not allow packages to utilize this field:

```
Error: building package failed: invalid content found in built package: found 1 validation error:
   1. file "....yml" is invalid: field 0.fields.0.fields.0.type: 0.fields.0.fields.0.type must be one of the following: "alias", "histogram", "constant_keyword", "text", "match_only_text", "keyword", "long", "integer", "short", "byte", "double", "float", "half_float", "scaled_float", "date", "date_nanos", "boolean", "binary", "integer_range", "float_range", "long_range", "double_range", "date_range", "ip_range", "group", "geo_point", "object", "ip", "nested", "array", "flattened", "wildcard", "version", "unsigned_long"
   2. ```

**Comment by jsoriano** [comment]
Supporting this type may also need changes in Fleet, as it has additional required settings (`metrics` and `default_metric`). We will also need to think about how to represent these fields in the spec.

**Comment by ruflin** [comment]
I filed a specific issue for aggregate_metric_double type: https://github.com/elastic/package-spec/issues/457

For `histogram`, the following change exists: https://github.com/elastic/package-spec/pull/52 It made it in the package spec, it should be validated that it also works in Fleet.

**Comment by jsoriano** [comment]
Closing this in favour of https://github.com/elastic/package-spec/issues/457.

Regarding histograms, I guess it works, there are several integrations using it.
