### ISSUE TITLE
[Custom-agent deployer] Remove validation allowing one service only

### ISSUE THREAD

**Issue by agithomas** [elastic/package-spec#434]
There exist a validation to allow only one service in custom-agent

[Custom-agent spec](https://github.com/elastic/package-spec/blob/cc31d3387b1113e245da6c4a2040052318d09bd1/spec/integration/_dev/deploy/agent/custom-agent.spec.yml#L17)

This does not allow system testing configuration needing multiple services
'''
version: '2.3'
services:
  docker-custom-agent:
    image: docker.elastic.co/employees/agithomas/elastic-agent-oracle-client:0.1
    user: root
  oracle:
    image: docker.elastic.co/observability-ci/database-enterprise:12.2.0.1
    ports:
      - 1521:1521
      - 5500:5500
'''

This custom-agent.spec.yml need to be modified to allow multiple services.

**Comment by jsoriano** [comment]
Related to https://github.com/elastic/elastic-package/issues/997

**Comment by agithomas** [comment]
PR Link : https://github.com/elastic/package-spec/pull/436
