### ISSUE TITLE
Add support for aggregate_metric_double type

### ISSUE THREAD

**Issue by ruflin** [elastic/package-spec#457]
For TSDB data streams, the field type [aggregate_metric_double](https://www.elastic.co/guide/en/elasticsearch//reference/master/aggregate-metric-double.html) was introduced. It seems the field is currently not supported yet as when I started to use the field I got an error message and I couldn't find it in the spec.

Here is the yaml I tried out:

```
    - name: agg_metric_field
      type: aggregate_metric_double
      metrics: [ "min", "max", "sum", "value_count" ],
      default_metrics: "max"
```

**Comment by ruflin** [comment]
Note: I added a label `tsdb` to group all tsdb related issues together.

**Comment by jsoriano** [comment]
PR open for the package spec: https://github.com/elastic/package-spec/pull/500
Issue open for support in Kibana: https://github.com/elastic/kibana/issues/154867
