### ISSUE TITLE
Release input packages spec as GA

### ISSUE THREAD

**Issue by jsoriano** [elastic/package-spec#480]
Spec for input packages is currently in beta, what doesn't allow to release input packages as GA, as seen in https://github.com/elastic/integrations/pull/5347.

We have been already implementing some input packages, we can already have system tests and support is implemented in Kibana/Fleet. We should start considering to release the input package spec as GA. The spec should check that the kibana constraint is set for versions >= 8.8.0 https://github.com/elastic/package-spec/issues/480#issuecomment-1441537571.

Some code related to this:
* Input spec marked as beta in https://github.com/elastic/package-spec/blob/ff8286d0c40ad76bb082e9c8ea78f4551c2519c1/spec/input/spec.yml#L14
* Validation checking that packages using beta specs cannot be released as GA: https://github.com/elastic/package-spec/blob/ff8286d0c40ad76bb082e9c8ea78f4551c2519c1/code/go/internal/validator/folder_spec.go#L61-L63 
* Input test packages don't have GA versions:
  * `good_input`: https://github.com/elastic/package-spec/blob/ff8286d0c40ad76bb082e9c8ea78f4551c2519c1/test/packages/good_input/manifest.yml#L7
  * `sql_input`: https://github.com/elastic/package-spec/blob/ff8286d0c40ad76bb082e9c8ea78f4551c2519c1/test/packages/sql_input/manifest.yml#L7

**Comment by hop-dev** [comment]
@jsoriano I think we should add a check to only allow input packages to be GA if they have a condition for kibana version to be greater than or equal to 8.8.0 which is when we plan to make them GA in kibana, do you think that is reasonable? 

CC @kpollich

**Comment by jsoriano** [comment]
> @jsoriano I think we should add a check to only allow input packages to be GA if they have a condition for kibana version to be greater than or equal to 8.8.0 which is when we plan to make them GA in kibana, do you think that is reasonable?

Yes, I think this could be done.

**Comment by jsoriano** [comment]
@hop-dev if you do this task, I think that releasing the spec as GA is quite straight forward, it would be to remove the [`release: beta` line in the input spec](https://github.com/elastic/package-spec/blob/ff8286d0c40ad76bb082e9c8ea78f4551c2519c1/spec/input/spec.yml#L14,), and to have some test case, modify the `good_input` package version to `1.0.0`.

To implement the part of checking the version, you will probably need to add a new "semantic validation" rule. They are added here: https://github.com/elastic/package-spec/blob/ff8286d0c40ad76bb082e9c8ea78f4551c2519c1/code/go/internal/validator/spec.go#L70
To implement it, take a look to `ValidatePrerelease`, you probably want to do something similar, but checking the type of package, the version of the package and the kibana constraint.

Thanks!
