### ISSUE TITLE
[Change Proposal] Adding categories for Infrastructure Observability

### ISSUE THREAD

**Issue by SubhrataK** [elastic/package-spec#488]
Hi,

In continuation of our effort to re-define the integration categories and realign all the integrations to improve the overall user experience, we would like to get the following additional categories added to the list. The new categories have been discussed internally within the Observability group and have been arrived at after a consensus.

The categories to be added are: APM, Compute and Message Queues.

**Comment by mukeshelastic** [comment]
@SubhrataK thanks for creating the issue? Can you share what integrations will come under APM and Compute?

**Comment by jen-huang** [comment]
@mukeshelastic See here: https://github.com/elastic/integrations/pull/5123#issuecomment-1446061414

**Comment by mukeshelastic** [comment]
Thanks @jen-huang for the link.. @SubhrataK Agree with APM and Message Queues as categories. Not clear why we need compute as category though..

**Comment by SubhrataK** [comment]
@mukeshelastic I checked it again and I agree that we do not need Compute as an additional category but we should keep it as a Subcategory, since there are not many Integrations that belong to this category.

To summarise: We will add only APM and Message Queues as new categories for Observability.

**Comment by jlind23** [comment]
As stated by Jaime, message queue was added as a category [here](https://github.com/elastic/integrations/pull/5123/files)
@SubhrataK shall we close this issue or is this still relevant?
