### ISSUE TITLE
Add `Advanced Analytics (UEBA)` sub-category to integrations

### ISSUE THREAD

**Issue by susan-shu-c** [elastic/package-spec#499]
## Overview

For customer navigation, we'd like to add a new subcategory to integrations, since having all these packages under `Security` (which has 175 packages) makes it hard to discover.

Category name: `Security` > `Advanced Analytics (UEBA)` 

Related packages 
* ProblemChild (Living off the Land Detection)
* DGA
* DED (Data Exfiltration Detection)
* LMD (Lateral Movement Detection)

We can make the PRs for these in the `integrations` repo after this issue/ticket is resolved.

# Business & User Value:

- [ ] Users need a convenient view of all ML-based advanced detection packs within their space. We are building additional integration packages under this category. The category will significantly reduce user efforts, reduce user error, and aid in feature discovery.
- [ ] Elastic security (Entity Analytics Onboarding) workflow will leverage this filtered view in the user journey for discovering these packages. Without a reconciled view, the onboarding workflow will remain incomplete.

# Implementation tasks
- [x] Add to package-spec ([ref PR](https://github.com/elastic/package-spec/pull/471))
* https://github.com/elastic/package-spec/pull/515
- [x] Add to package-registry ([ref PR](https://github.com/elastic/package-registry/pull/953))
* https://github.com/elastic/package-registry/pull/997
- [x] Add to kibana ([ref PR](https://github.com/elastic/kibana/pull/135758))
* https://github.com/elastic/kibana/pull/155935
- [x] Release new version of package spec (contact @mrodm)
- [x] Release new version of elastic-package (contact @mrodm)
- [x] Release new version of package registry (contact @mrodm)

# Mockup:
![Screenshot 2023-04-12 at 9 22 19 AM](https://user-images.githubusercontent.com/23287722/231551128-93ffecb4-2d4d-4a18-822d-54451487b883.png)

## Related tickets

* https://github.com/elastic/integrations/pull/5123

**Comment by susan-shu-c** [comment]
@jen-huang mentioned that this should be a subcategory under Security, which would then look like this ([source](https://github.com/elastic/ingest-dev/issues/1349)):

<img width="1030" alt="Screenshot 2023-04-12 at 3 30 50 PM" src="https://user-images.githubusercontent.com/23287722/231564947-a5087ec1-3568-45f5-90f3-78ae758e0b6d.png">

So then it would be Security > Advanced Analytics (UEBA), since the goal of the [recent cleanup](https://github.com/elastic/integrations/pull/5123) was to reduce the high level categories to only a few - [link](https://github.com/elastic/ingest-dev/issues/1349)

@SourinPaul

**Comment by SourinPaul** [comment]
> So then it would be Security > Advanced Analytics (UEBA), since the goal of the [recent cleanup](https://github.com/elastic/integrations/pull/5123) was to reduce the high-level categories to only a few

This sounds perfect!

**Comment by jen-huang** [comment]
Adding this as a new subcategory under Security makes sense to me. Per discussion with @susan-shu-c, the ML team will handle the implementation work. I have added the list of tasks to the parent issue description.

**Comment by susan-shu-c** [comment]
Thank you, @jen-huang for approving; I'll take it from here 👍

**Comment by susan-shu-c** [comment]
Hi, @mrodm I've created various PRs based on Jen's instructions, please let me know if there's anything I'm missing!

* https://github.com/elastic/package-spec/pull/515
* https://github.com/elastic/package-registry/pull/997
* https://github.com/elastic/kibana/pull/155935

**Comment by mrodm** [comment]
Hi @susan-shu-c , these PRs should be enough. Afterwards, some releases (package-spec, elastic-package and package-registry) would need to be performed.

**Comment by susan-shu-c** [comment]
Sounds good, @mrodm . I don't have permissions to merge in `package-spec`, but I will merge the other 2 PRs in Kibana, package-registry

**Comment by jsoriano** [comment]
> Sounds good, @mrodm . I don't have permissions to merge in `package-spec`, but I will merge the other 2 PRs in Kibana, package-registry

I have merged the package-spec one.

**Comment by susan-shu-c** [comment]
Thanks @jsoriano I merged the other two!

**Comment by susan-shu-c** [comment]
Thank you @mrodm , the 3 PRs have now been merged 👍

**Comment by susan-shu-c** [comment]
Thank you @mrodm I've gotten the integrations repo PR merged! Which adds the subcategory to the respective packagesI think we're all good now 😁

**Comment by susan-shu-c** [comment]
Nice, it's live!

<img width="1134" alt="Screenshot 2023-06-08 at 12 09 18 PM" src="https://github.com/elastic/package-spec/assets/23287722/9c070092-7168-4d4f-b38f-8a5c2f29963e">
<img width="1095" alt="Screenshot 2023-06-08 at 12 09 28 PM" src="https://github.com/elastic/package-spec/assets/23287722/54dfa730-0ef0-4923-9ace-01839d1c074b">
