### ISSUE TITLE
Support `store` option in fields spec

### ISSUE THREAD

**Issue by felixbarny** [elastic/package-spec#548]
Support the [store](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-store.html) mapping parameter in https://github.com/elastic/package-spec/blame/main/spec/integration/data_stream/fields/fields.spec.yml.

This blocks TSDB adoption for packages that are using `text` fields as synthetic _source requires the `store` option be set to `true` for `text` fields.

See also https://github.com/elastic/elasticsearch/issues/96254

**Comment by agithomas** [comment]
What may be needed here are two things

1. Permit `text` to be an allowed dimension type
2. Allow `store: true` in field mappings.

**Comment by jsoriano** [comment]
> Permit `text` to be an allowed dimension type

`text` doesn't seem to be allowed by Elasticsearch, if there is a use case for this, it should be requested to Elasticsearch. Find allowed types here: https://www.elastic.co/guide/en/elasticsearch/reference/8.9/tsds.html#time-series-dimension

> Allow `store: true` in field mappings.

> This blocks TSDB adoption for packages that are using `text` fields as synthetic _source requires the `store` option be set to `true` for `text` fields.

If synthetic source requires `store: true` for `text` fields, maybe Fleet should take care of this. So when a data stream template is installed with synthetic source enabled, Fleet sets store to true automatically for all text fields. This way developers wouldn't need to remember to set this option for their text fields. What do you think about this option?

Are there more use cases for `store`?

**Comment by agithomas** [comment]
> So when a data stream template is installed with synthetic source enabled, Fleet sets store to true automatically for all text fields

@martijnvg , apart from `text`, are there any more types that permit `dimension: true` annotation by setting `store:true`?

**Comment by martijnvg** [comment]
> apart from text, are there any more types that permit synthetic source by setting store:true? If there exist, we can combine the requirements.

If for some reason a keyword field has been configured to not have doc values then synthetic source can also synthesise it from a stored field if for the keyword field `store` has been set to true.

> I think, having to remember less configuration is certainly convenient to the developers.

Yes, we're going to implement this: elastic/elasticsearch97039

**Comment by jsoriano** [comment]
> > I think, having to remember less configuration is certainly convenient to the developers.
> 
> Yes, we're going to implement this: [elastic/elasticsearch#97039](https://github.com/elastic/elasticsearch/issues/97039)

This would be ideal.

@felixbarny @agithomas is it ok to wait till this is implemented in Elasticsearch? or you would still need an alternative in the meantime?

**Comment by agithomas** [comment]
> @felixbarny @agithomas is it ok to wait till this is implemented in Elasticsearch? or you would still need an alternative in the meantime?

Today we discussed on this point and we are plan to convert the type to `keyword` as an alternative. So, I am good to wait.

**Comment by jsoriano** [comment]
Thanks Agi for confirming. Closing this then by now, please reopen if you end up finding that something else is needed in packages or Fleet.
