### ISSUE TITLE
[Change Proposal] Support disabling validation rules per package

### ISSUE THREAD

**Issue by jsoriano** [elastic/package-spec#558]
Add support to disable validation rules per package. This will help to disable certain validations on exceptional cases, or till some feature is fully supported.

Related to #342.

**Comment by mrodm** [comment]
Changes introduced in package-spec to support this must be added into:
- [ ] package-storage-infra: add support to skip the required errors defined in each package when running the publishing job.
- [ ] elastic-package: add support to validate and filter errors according to the errors configuration file.

**Comment by mrodm** [comment]
Closing this issue since elastic-package and package-storage-infra are already using filtering based on codes.
