### ISSUE TITLE
Add package validator in typescript

### ISSUE THREAD

**Issue by skh** [elastic/package-spec#58]
To be able to use the package validation from this repository in EPM in Kibana, we need to publish an npm package to the `@elastic` namespace on https://www.npmjs.com/ . From there, we can import the package in Kibana like any other npm package.

Publishing to npmjs.com can be done manually whenever we have a release.

- [ ] Create a subdirectory `code/typescript`
- [ ] create a standard npm package there
- [ ] implement a stub validator
- [ ] add tests & integrate into CI of this repository
- [ ] document how to use a local checkout of the validator in a local checkout of kibana for development
- [ ] publish to npm
- [ ] automate publishing to npm?
- [ ] implement the real validator

**Comment by skh** [comment]
cc @jfsiii 

Feel free to adjust the initial description, this is mostly a brain dump of mine.

**Comment by jen-huang** [comment]
Closing as won't fix: we haven't come across the need for this in the past few years, so the effort of doing this work won't provide much benefits.
