### ISSUE TITLE
Create traces data type

### ISSUE THREAD

**Issue by jalvz** [elastic/package-spec#68]
The spec defines 2 data types: metrics and logs (https://github.com/elastic/package-spec/blob/e7102f8cbd392d977bb2a21b12674dbe2ae8b985/versions/1/data_stream/manifest.spec.yml#L93-L95).

For the upcoming APM integration we need a new `traces` data type.

**Comment by ruflin** [comment]
If we add a new data type, this should also be added to Elasticsearch @dakrone

**Comment by jalvz** [comment]
Thanks @ruflin, anything else I should be aware of? 
Regarding EPR is just enough to add the new type to the enum above?

**Comment by ruflin** [comment]
For EPR, yes. It will also need to be added to Kibana to make sure the Kibana index pattern gets generated. @neptunian
