### ISSUE TITLE
Validation: Kibana asset IDs should not contain `-ecs` suffix

### ISSUE THREAD

**Issue by ycombinator** [elastic/package-spec#71]
Per the discussion starting from https://github.com/elastic/integrations/issues/269#issuecomment-693368174, it was agreed that Kibana asset IDs in Integrations packages should not contain the `-ecs` suffix. Also, any asset titles/labels/markdown links/etc. should not contain the ` ECS` suffix either (per @andrewkroh's suggestion here: https://github.com/elastic/integrations/issues/339#issuecomment-717238777). We should add validation to the spec for this.

This issue will be resolved via multiple PRs (please keep the list below updated with links to the various PRs)
* [x] Validate that Kibana object filenames do not contain the `-ecs` suffix: 
* [ ] Validate that titles/labels/markdown links/etc. within Kibana object files should not contain the ` ECS` suffix:

**Comment by ycombinator** [comment]
Also validate that the title of the assets doesn't contain an `ECS` suffix, per @andrewkroh's suggestion here: https://github.com/elastic/integrations/issues/339#issuecomment-717238777.

**Comment by jsoriano** [comment]
This doesn't seem to be a problem anymore, the import tool removed these suffixes, and new integrations shouldn't have it.

Looking to the integrations repository, I have only found the `awsfargate` integration to contain dashboards with titles with the ECS prefix. So probably it would be enough with fixing these dashboards, and it is not worth to add an explicit validation for this.

@elastic/obs-cloud-monitoring could you please remove `ECS` from the titles of the dashboards in the `awsfargate` package? Thanks!

**Comment by kaiyan-sheng** [comment]
@jsoriano Sorry I don't see `-ecs` suffix in dashboard/lens/visualization file names. Are we also checking `ECS` in like title names? I think `ECS` here in awsfargate dashboard might represent Amazon Elastic Compute Cloud instead.

**Comment by zmoog** [comment]
Yep! The ECS in the AWS Fargate integration stands for (Amazon) Elastic Container Service. 

Do you think we should remove it?

**Comment by jsoriano** [comment]
Ah ok, sorry, this is perfectly fine then! I think we can close this. Thanks!

**Comment by zmoog** [comment]
We could quickly expand the acronym in some places, but in others, it can look weird because of space constraints and would not match the names AWS uses on their web console.

Here are a couple of examples from titles in lens and visualizations:

![awsfargate-integration-overview with annotations](https://user-images.githubusercontent.com/25941/190338549-005fb37a-68aa-40bb-9e73-bb8817e14dd6.png)

Does this constraint apply to any title, or just dashboards'?

@jsoriano, let us know what you think.

**Comment by zmoog** [comment]
Ops, sorry, forget my last comment; I missed your last one! 😄

**Comment by jsoriano** [comment]
> Does this constraint apply to any title, or just dashboards'?

It applies to titles of dashboards and visualizations, but only for a legacy suffix we added to ECS vs pre-ECS dashboards, being ECS the Elastic Common Schema. If there are other things called ECS, it is fine to use this name :slightly_smiling_face:
