### ISSUE TITLE
Allow `index.mapping.ignore_malformed` to be set inside index templates

### ISSUE THREAD

**Issue by kcreddy** [elastic/package-spec#730]
Currently for `elasticsearch_index_template`, only few properties are allowed to be set under `index.mapping`: https://github.com/elastic/package-spec/blob/main/spec/integration/data_stream/manifest.spec.yml#L211-L221
We need to allow `index.mapping.ignore_malformed` to be set inside index templates.

The issue without this property:
When a transform is involved, the source datastream (by default) contains `index.mapping.ignore_malformed: true`. This ingests any malformed documents, for example in: https://github.com/elastic/integrations/issues/9360, a value of `178.21.14.0/23` is ingested into the source datastream's  field `threat.indicator.ip`. However, the transform crashes to index into the destination because (by default) `index.mapping.ignore_malformed` is `false` It is not possible to override this value as it follows the same [index template definition](https://github.com/elastic/package-spec/blob/main/spec/integration/elasticsearch/transform/manifest.spec.yml#L11-L14).

**Comment by jsoriano** [comment]
@kcreddy thanks for opening the issue. To be sure I understand, the defaults for `ignore_malformed` in data streams and in transforms is different?
If that's the case, maybe we want to always set `index.mapping.ignore_malformed` to `true` for integrations? There would be any case where this is not wanted?
If we want to always set `ignore_malformed` to `true`, we can make this from Fleet.

**Comment by andrewkroh** [comment]
> If we want to always set ignore_malformed to true [for data stream and transform indices], we can make this from Fleet.

I think that is what we should do. The least surprising thing from a developer standpoint would be for any data streams or indices that get created through Fleet integrations to have similar configurations including `ignore_malformed`.

**Comment by jsoriano** [comment]
Agree, opened issue in Kibana repo https://github.com/elastic/kibana/issues/179445. And closing this one.

Thanks!
