### ISSUE TITLE
Move test packages outside golang code folder

### ISSUE THREAD

**Issue by ycombinator** [elastic/package-spec#77]
Currently, we keep a number of test packages in [`code/go/internal/validator/test/packages`](https://github.com/elastic/package-spec/tree/master/code/go/internal/validator/test/packages). This is okay as long as we only have a Golang validator for the package spec. However, as we add more language validators (e.g. [for TypeScript](https://github.com/elastic/package-spec/issues/58)), we might want to move the test packages to a more common location.

cc: @mtojek @skh

**Comment by skh** [comment]
cc @jfsiii
