### ISSUE TITLE
Add field validation for `ilm_policy` field in package spec.

### ISSUE THREAD

**Issue by kevinlog** [elastic/package-spec#92]
We now have a field to define a custom `ilm_policy` for a `data stream` in a package definition.   Since the `ilm_policy` is shipped with the package itself, we should introduce field validation.

See this PR for details on the `ilm_policy` field: https://github.com/elastic/package-spec/pull/90

**Comment by jsoriano** [comment]
Hey @kevinlog,

I am taking a look to this issue, but I am not sure about what validations we can do.

For example I see that the `findings` data stream of the Cloud Security Posture package indicates as ILM policy `logs-cloud_security_posture.findings-default_policy`. It also defines an ILM policy in a file called `default_policy.json`.

Should we validate that the ILM policy matches with something like the following pattern?
```
{data stream type}-{package name}.{data stream name}-{ilm file name without extension}
```

**Comment by kevinlog** [comment]
@jsoriano it has been a while since I opened this ticket, so I am refreshing my memory.

I believe the original reason for opening was that we added support for a custom ilm policy, but there wasn't any validation for the naming convention, [some context here](https://github.com/elastic/package-spec/pull/90#discussion_r536063297).

The convention above looks good to me and would also work with the `ilm_policy` we defined here: https://github.com/elastic/endpoint-package/tree/master/package/endpoint/data_stream/collection

Our data_stream name: `collection`
ilm_policy: `logs-endpoint.collection-diagnostic`
