### ISSUE TITLE
Replace github.com/rakyll/statik with go:embed

### ISSUE THREAD

**Issue by ycombinator** [elastic/package-spec#99]
With Go 1.16, we get support for static file embedding in Golang itself. I don't have authoritative resources to link to yet, but here are some others that might help for now:

- https://www.reddit.com/r/golang/comments/jkdjgw/complete_goembed_support_has_just_landed/gaiy7na/
- https://www.reddit.com/r/golang/comments/kfm4ly/embed_files_in_go_using_new_embed_package_in_go/

**Comment by ycombinator** [comment]
Video tutorial showing the usage of `go:embed`: https://www.youtube.com/watch?v=YoDGTwwQTso

**Comment by ruflin** [comment]
Nice, thanks for sharing. I think there are other places where we can use this feature.
